### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by Lozenger17** [pjpscriv/day#1]
You should have a drop-down menu to choose location

**Comment by lotumusic** [comment]
I second this!

**Comment by Lozenger17** [comment]
Or like, share a location from Google maps and then drop it into Day

**Comment by pjpscriv** [comment]
### Lil research notes
- Maps autocomplete service for that sweet autocomplete: https://developers.google.com/maps/documentation/places/web-service/autocomplete
- And looks like there's a bunch of services that can turn place names into coords:
  - https://www.google.com/search?q=input+get+lat+long+from+place+name
  - Could use Google Maps API for this too or could try an alt:
  - https://www.latlong.net/convert-address-to-lat-long.html

**Comment by pjpscriv** [comment]
Alright so we've got a little bit of the way there. Tell me what you guys think! https://pjpscriv.github.io/day/

### Main things done:

- Updated the UI to be a bit more professional: proper buttons, text fields etc
- The date field now has a date picker you can use to pick different dates
- Lat + long are now text fields that can be edited directly as opposed to just shifting with the `+`/`-` buttons
- A "Location by name" field added (doesn't do anything atm)
- A button to switch between lat/long and location-by-name added


### Extra notes:

**To Do:**

- Wire up the location-by-name to the Google Maps API to provide auto-complete suggestions as the user types then get the lat-long info when the user selects one. This should be pretty straightforward, I found the Maps API to do this, they provide a library and they provide $200 worth of calls to the API before they start charging.
- Add a way to reset the date back to current day

**Bug:**

- Looks like time zones are properly accounted for and all the times are displayed in NZ local time, so if you shift to a position on the opposite side of the world the sunrise / sunset times will be in NZ time and the "clock" will be flipped

**Comment by pjpscriv** [comment]
THIS DONE NOW BABY ONLY TOOK A YEAR @Lozenger17 @connortaumoepeau

**Comment by lotumusic** [comment]
It’s slay. Gotta get the time in

Ngā mihi,
Connor Taumoepeau
________________________________

**Comment by Lozenger17** [comment]
Well done you. What a journey!
